/*
 * Bake the procedural craft_textures atlas into a const C array.
 *
 * Linked against the *unbaked* craft_blocks.c (CRAFT_TEXTURES_BAKED
 * NOT defined), so craft_textures is the writable BSS storage with
 * a working craft_blocks_build_textures(). We run the build, dump
 * the resulting pixels as a const array, and the device + host
 * builds then read that file instead of running the init at boot
 * — freeing ~32 KB of SRAM.
 */
#include <stdio.h>
#include <stdlib.h>
#include "craft_blocks.h"

extern uint16_t craft_textures[CRAFT_TEX_COUNT * CRAFT_TEX_PIXELS];

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output.c>\n", argv[0]);
        return 1;
    }

    craft_blocks_build_textures();

    FILE *f = fopen(argv[1], "w");
    if (!f) { perror("fopen"); return 1; }

    fprintf(f,
        "/* AUTO-GENERATED by tools/bake_textures — DO NOT EDIT.\n"
        " * Regenerated whenever craft_blocks.c changes. */\n"
        "#include \"craft_blocks.h\"\n"
        "\n"
        "const uint16_t craft_textures_baked[CRAFT_TEX_COUNT * CRAFT_TEX_PIXELS] = {\n");

    int N = CRAFT_TEX_COUNT * CRAFT_TEX_PIXELS;
    for (int i = 0; i < N; i++) {
        if ((i & 15) == 0) fprintf(f, "    ");
        fprintf(f, "0x%04x,", craft_textures[i]);
        fputc(((i & 15) == 15) ? '\n' : ' ', f);
    }
    fprintf(f, "};\n");
    fclose(f);
    return 0;
}
